use crate::bench_lab::sweep::SweepPoint;

/// Fit the exponent `b` in `wall_p99 ≈ a·nᵇ` by ordinary least squares on the
/// log-log points `(ln population, ln wall_p99_us)`. `b ≈ 1` is linear `O(n)`,
/// `b ≈ 2` is `O(n²)`: a candidate that lowers `b` improved the *scaling class*,
/// not merely the constant factor — the highest-value signal for the cloud
/// triage hunt, whose whole point is finding growth-rate wins cheaply at ≤10k.
///
/// Returns `None` (a defined "growth-rate unavailable" sentinel, never `NaN`
/// or a panic) when fewer than two usable points survive, or when every
/// population is identical so no slope is defined. Points with a non-positive
/// population or p99 are dropped before the fit, since their log is undefined.
pub fn fit_growth_exponent(points: &[SweepPoint]) -> Option<f64> {
    let pts: Vec<(f64, f64)> = points
        .iter()
        .filter(|p| p.population > 0 && p.wall_p99_us > 0.0)
        .map(|p| ((p.population as f64).ln(), p.wall_p99_us.ln()))
        .collect();
    if pts.len() < 2 {
        return None;
    }
    let n = pts.len() as f64;
    let sx: f64 = pts.iter().map(|(x, _)| *x).sum();
    let sy: f64 = pts.iter().map(|(_, y)| *y).sum();
    let sxx: f64 = pts.iter().map(|(x, _)| x * x).sum();
    let sxy: f64 = pts.iter().map(|(x, y)| x * y).sum();
    // denom = n·Σx² − (Σx)² is zero exactly when all x (log populations) match.
    let denom = n * sxx - sx * sx;
    if denom.abs() < f64::EPSILON {
        return None;
    }
    Some((n * sxy - sx * sy) / denom)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Only `population` and `wall_p99_us` matter to the fit; the rest is filler.
    fn pt(pop: usize, p99: f64) -> SweepPoint {
        SweepPoint { population: pop, wall_mean_us: p99, wall_p99_us: p99, within_budget: true }
    }

    /// Points generated by `t = a·n` must recover exponent b ≈ 1 (linear O(n)).
    #[test]
    fn linear_data_fits_exponent_near_one() {
        let a = 0.5;
        let pts: Vec<SweepPoint> = [1000, 2000, 4000, 7000, 10000]
            .iter()
            .map(|&n| pt(n, a * n as f64))
            .collect();
        let b = fit_growth_exponent(&pts).expect("two+ points fit");
        assert!((b - 1.0).abs() < 1e-6, "linear must fit b≈1, got {b}");
    }

    /// Points generated by `t = a·n²` must recover exponent b ≈ 2 (quadratic O(n²)).
    #[test]
    fn quadratic_data_fits_exponent_near_two() {
        let a = 1e-3;
        let pts: Vec<SweepPoint> = [1000, 2000, 4000, 7000, 10000]
            .iter()
            .map(|&n| pt(n, a * (n as f64).powi(2)))
            .collect();
        let b = fit_growth_exponent(&pts).expect("two+ points fit");
        assert!((b - 2.0).abs() < 1e-6, "quadratic must fit b≈2, got {b}");
    }

    /// `t = a·n·ln n` grows faster than linear but far slower than quadratic;
    /// its fitted exponent must land strictly between 1 and 2 (near ~1.1 here).
    #[test]
    fn n_log_n_data_fits_between_one_and_two() {
        let a = 0.05;
        let pts: Vec<SweepPoint> = [1000, 2000, 4000, 7000, 10000]
            .iter()
            .map(|&n| pt(n, a * n as f64 * (n as f64).ln()))
            .collect();
        let b = fit_growth_exponent(&pts).expect("two+ points fit");
        assert!(b > 1.0 && b < 1.4, "n·log n must fit 1<b<1.4, got {b}");
    }

    /// Edge case most often skipped: no data / one point → no slope is defined,
    /// so the fit returns the None sentinel rather than NaN or a panic.
    #[test]
    fn empty_or_single_point_returns_none() {
        assert!(fit_growth_exponent(&[]).is_none(), "empty → None");
        assert!(fit_growth_exponent(&[pt(1000, 500.0)]).is_none(), "one point → None");
    }

    /// Two points at the SAME population give a zero-variance x-axis: the slope
    /// is undefined (division by zero), so the guard must return None, not NaN.
    #[test]
    fn identical_populations_return_none() {
        let pts = [pt(5000, 100.0), pt(5000, 900.0)];
        assert!(fit_growth_exponent(&pts).is_none(), "no x-variance → None");
    }

    /// Non-positive population/p99 points (undefined log) are dropped; if that
    /// leaves fewer than two usable points, the fit degrades to None cleanly.
    #[test]
    fn non_positive_points_are_filtered() {
        let pts = [pt(0, 500.0), pt(1000, 0.0), pt(2000, 1000.0)];
        // Only (2000, 1000) survives the filter → one usable point → None.
        assert!(fit_growth_exponent(&pts).is_none(), "one usable point after filter → None");
    }
}
