/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize panic handler (MUST be called before creating SimulationEngine)
 *
 * This ensures Rust panics are logged to stderr so Electron can see them.
 * Without this, panics would be silent and difficult to debug.
 */
export declare function initLogger(): void
/**
 * SimulationEngine - The NAPI bridge to Bevy ECS
 *
 * **Lifecycle:**
 * 1. `new()` - Create engine (allocates resources)
 * 2. `start(count, path, callback)` - Spawn Bevy thread
 * 3. `get_buffer()` - Read positions (zero-copy, called every frame)
 * 4. `spawn_creatures()`, `kill_all()` - Send commands
 * 5. Drop - Clean shutdown (waits for thread to exit)
 *
 * **Thread Safety:**
 * - DoubleBuffer: Lock-free atomic swap (zero contention)
 * - Commands: Bounded channel (prevents overflow)
 * - Telemetry: ThreadsafeFunction (JavaScript callback)
 */
export declare class SimulationEngine {
  /** Create new SimulationEngine (does not start simulation yet) */
  constructor()
  /**
   * Start simulation with initial creature count
   *
   * # Arguments
   * * `count` - Initial creature count
   * * `assets_path` - Path to config directory (must exist)
   * * `callback` - JavaScript function for telemetry updates
   * * `save_state_path` - Optional path to save state file (loads if exists)
   *
   * # Errors
   * * Assets path does not exist
   * * Simulation already running
   *
   * # Example (JavaScript)
   * ```js
   * const sim = new SimulationEngine();
   * // Start fresh with 150K creatures
   * sim.start(150000, '/path/to/assets', (telemetry) => { }, null);
   *
   * // Or resume from save state
   * sim.start(0, '/path/to/assets', (telemetry) => { }, 'save-states/latest.msgpack');
   * ```
   */
  start(count: number, assetsPath: string, callback: (...args: any[]) => any, saveStatePath?: string | undefined | null): void
  /**
   * Get read-only buffer for zero-copy access from JavaScript
   *
   * **Performance:** Instant (just returns Float32Array view)
   *
   * **Layout (SoA):**
   * ```
   * [ID₁, ID₂, ..., IDₙ, X₁, X₂, ..., Xₙ, Y₁, Y₂, ..., Yₙ, Rot₁, Rot₂, ..., Rotₙ]
   * ```
   *
   * # Example (JavaScript)
   * ```js
   * const buffer = sim.getBuffer();
   * const creatureCount = buffer.length / 4;
   * const xOffset = creatureCount;
   * const yOffset = creatureCount * 2;
   *
   * for (let i = 0; i < creatureCount; i++) {
   *   sprite.x = buffer[xOffset + i];
   *   sprite.y = buffer[yOffset + i];
   * }
   * ```
   */
  getBuffer(): Float32Array
  /**
   * Get target simulation tick rate (Hz)
   *
   * JavaScript should query this to calculate appropriate polling rates.
   * Recommended: Poll at 2x this rate to ensure no frames are missed.
   */
  getTargetHz(): number
  /**
   * Resize buffer to accommodate new creature count
   *
   * **Use case:** If entity count changes significantly
   *
   * # Arguments
   * * `new_count` - New creature count
   */
  resizeBuffer(newCount: number): void
  /**
   * Spawn creatures at random positions
   *
   * # Arguments
   * * `count` - Number of creatures to spawn
   *
   * # Errors
   * * Simulation not started
   * * Command queue full (128 capacity)
   *
   * # Example (JavaScript)
   * ```js
   * sim.spawnCreatures(100); // Spawn 100 creatures
   * ```
   */
  spawnCreatures(count: number): void
  /**
   * Spawn creature at specific position
   *
   * # Arguments
   * * `x` - X coordinate
   * * `y` - Y coordinate
   *
   * # Errors
   * * Simulation not started
   * * Command queue full
   */
  spawnCreatureAt(x: number, y: number): void
  /**
   * Despawn all creatures
   *
   * # Errors
   * * Simulation not started
   * * Command queue full
   */
  killAll(): void
  /**
   * Load trial configuration
   *
   * # Arguments
   * * `template` - Trial template name (e.g., "flocking_test")
   */
  loadTrial(template: string): void
  /**
   * Select a creature for perception debug visualization
   *
   * When a creature is selected, the simulation will include detailed
   * perception data (position, range, neighbors) in telemetry updates.
   *
   * # Arguments
   * * `creature_id` - The creature ID to select, or None to clear selection
   *
   * # Example (JavaScript)
   * ```js
   * // Select creature 123 for debug visualization
   * sim.selectCreatureDebug(123);
   *
   * // Clear selection
   * sim.selectCreatureDebug(null);
   * ```
   */
  selectCreatureDebug(creatureId?: number | undefined | null): void
  /**
   * Get full telemetry snapshot (all 45+ metrics)
   *
   * **Performance:** 3-8µs per call (negligible overhead)
   *
   * # Returns
   * JSON string with complete telemetry data:
   * - tick, creatureCount (always included)
   * - systemTimings (always included)
   * - hardwareMetrics (dev-tools only)
   * - parallelizationMetrics (dev-tools only)
   *
   * # Example (JavaScript)
   * ```js
   * const telemetryJson = sim.getTelemetry();
   * const data = JSON.parse(telemetryJson);
   * console.log('Tick:', data.tick);
   * console.log('Creatures:', data.creatureCount);
   * console.log('Movement system:', data.systemTimings.movementUs, 'μs');
   * ```
   */
  getTelemetry(): string
  /**
   * Get current simulation tick
   *
   * # Returns
   * Current tick number (0 if not started or error)
   *
   * # Example (JavaScript)
   * ```js
   * const tick = sim.getTick();
   * console.log('Current tick:', tick);
   * ```
   */
  getTick(): number
  /**
   * Get simulation tick rate (Hz)
   *
   * # Returns
   * Tick rate in Hz (default: 30.0)
   *
   * # Example (JavaScript)
   * ```js
   * const tickRate = sim.getTickRate();
   * console.log('Tick rate:', tickRate, 'Hz');
   * ```
   */
  getTickRate(): number
  /**
   * Get current creature count
   *
   * # Returns
   * Number of living creatures (0 if not started or error)
   *
   * # Example (JavaScript)
   * ```js
   * const count = sim.getCreatureCount();
   * console.log('Creature count:', count);
   * ```
   */
  getCreatureCount(): number
  /**
   * Get the actual number of creatures in the current buffer
   *
   * This returns the exact count of creatures that were exported to the buffer
   * on the last tick. Unlike getCreatureCount() which reads from telemetry
   * (updated every 30 ticks), this is always current.
   *
   * # Returns
   * Number of creatures in buffer (updated every tick)
   *
   * # Example (JavaScript)
   * ```js
   * const bufferCount = sim.getBufferCreatureCount();
   * console.log('Buffer creature count:', bufferCount);
   * ```
   */
  getBufferCreatureCount(): number
  /**
   * Get buffer capacity statistics
   *
   * Returns capacity, used count, and utilization percentage for monitoring
   *
   * # Returns
   * JSON string with buffer stats: { capacity, used, utilizationPct }
   *
   * # Example (JavaScript)
   * ```js
   * const stats = JSON.parse(sim.getBufferStats());
   * console.log(`Buffer: ${stats.used}/${stats.capacity} (${stats.utilizationPct}%)`);
   * ```
   */
  getBufferStats(): string
  /**
   * Stop simulation gracefully (with optional shutdown save)
   *
   * **Note:** Also called automatically when SimulationEngine is dropped
   */
  stop(): void
  /**
   * Shutdown simulation with final save state
   *
   * Sets the running flag to false, which triggers the thread to:
   * 1. Exit the run loop
   * 2. Create a shutdown save (if enabled, lines 293-301)
   * 3. Clean exit
   *
   * Should be called before process exit for proper state preservation.
   */
  shutdown(): void
  /**
   * Get perception debug buffer
   *
   * Returns Float32Array with perception debug data for selected creature.
   *
   * **Layout:**
   * - [0]: has_data (1.0 = valid, 0.0 = no selection)
   * - [1]: target_id
   * - [2]: target_x
   * - [3]: target_y
   * - [4]: perception_range
   * - [5]: neighbor_count
   * - [6..6+64]: neighbor_ids
   * - [6+64..6+128]: neighbor_xs
   * - [6+128..6+192]: neighbor_ys
   *
   * # Example (JavaScript)
   * ```js
   * const debug = simulation.getPerceptionDebug();
   * if (debug[0] > 0.5) { // has_data
   *   const targetX = debug[2];
   *   const targetY = debug[3];
   *   const range = debug[4];
   *   const neighborCount = debug[5];
   *   // Draw circle at (targetX, targetY) with radius `range`
   *   // Draw lines to neighbors at indices 6+i, 70+i, 134+i
   * }
   * ```
   */
  getPerceptionDebug(): Float32Array
}
