/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize panic handler (MUST be called before creating SimulationEngine)
 *
 * This ensures Rust panics are logged to stderr so Electron can see them.
 * Without this, panics would be silent and difficult to debug.
 */
export declare function initLogger(): void
/**
 * SimulationEngine - The NAPI bridge to Bevy ECS
 *
 * **Lifecycle:**
 * 1. `new()` - Create engine (allocates resources)
 * 2. `start(count, path, callback)` - Spawn Bevy thread
 * 3. `get_buffer()` - Read positions (zero-copy, called every frame)
 * 4. `spawn_creatures()`, `kill_all()` - Send commands
 * 5. Drop - Clean shutdown (waits for thread to exit)
 *
 * **Thread Safety:**
 * - DoubleBuffer: Lock-free atomic swap (zero contention)
 * - Commands: Bounded channel (prevents overflow)
 * - Telemetry: ThreadsafeFunction (JavaScript callback)
 */
export declare class SimulationEngine {
  /** Create new SimulationEngine (does not start simulation yet) */
  constructor()
  /**
   * Start simulation with initial creature count
   *
   * # Arguments
   * * `count` - Initial creature count
   * * `assets_path` - Path to config directory (must exist)
   * * `callback` - JavaScript function for telemetry updates
   * * `save_state_path` - Optional path to save state file (loads if exists)
   *
   * # Errors
   * * Assets path does not exist
   * * Simulation already running
   *
   * # Example (JavaScript)
   * ```js
   * const sim = new SimulationEngine();
   * // Start fresh with 150K creatures
   * sim.start(150000, '/path/to/assets', (telemetry) => { }, null);
   *
   * // Or resume from save state
   * sim.start(0, '/path/to/assets', (telemetry) => { }, 'save-states/latest.msgpack');
   * ```
   */
  start(count: number, assetsPath: string, callback: (...args: any[]) => any, saveStatePath?: string | undefined | null): void
  /**
   * Get read-only buffer for zero-copy access from JavaScript
   *
   * **Performance:** Instant (just returns Float32Array view)
   *
   * **Layout (SoA):**
   * ```
   * [ID₁...IDₙ, X₁...Xₙ, Y₁...Yₙ, Rot₁...Rotₙ, Size₁...Sizeₙ]
   * ```
   *
   * # Example (JavaScript)
   * ```js
   * const buffer = sim.getBuffer();
   * const creatureCount = buffer.length / 5;
   * const xOffset = creatureCount;
   * const yOffset = creatureCount * 2;
   * const rotOffset = creatureCount * 3;
   * const sizeOffset = creatureCount * 4;
   *
   * for (let i = 0; i < creatureCount; i++) {
   *   sprite.x = buffer[xOffset + i];
   *   sprite.y = buffer[yOffset + i];
   *   sprite.scale = buffer[sizeOffset + i];
   * }
   * ```
   */
  getBuffer(): Float32Array
  /**
   * Fill a JS-owned buffer with creature data (zero-allocation)
   *
   * **MEMORY FIX:** JS creates buffer once, Rust fills it every poll.
   * This avoids the per-call Float32Array allocation that V8 doesn't GC properly.
   *
   * # Arguments
   * * `buffer` - JS-owned Float32Array to fill (must be large enough)
   *
   * # Returns
   * Number of creatures written (buffer layout: [IDs, Xs, Ys, Rotations])
   *
   * # Safety
   * Uses as_mut() which is safe because JS polling is single-threaded and
   * we only access the buffer during this synchronous call.
   */
  fillBuffer(buffer: Float32Array): number
  /**
   * Get target simulation tick rate (Hz)
   *
   * JavaScript should query this to calculate appropriate polling rates.
   * Recommended: Poll at 2x this rate to ensure no frames are missed.
   */
  getTargetHz(): number
  /**
   * Resize buffer to accommodate new creature count
   *
   * **Use case:** If entity count changes significantly
   *
   * # Arguments
   * * `new_count` - New creature count
   */
  resizeBuffer(newCount: number): void
  /**
   * Spawn creatures at random positions
   *
   * # Arguments
   * * `count` - Number of creatures to spawn
   *
   * # Errors
   * * Simulation not started
   * * Command queue full (128 capacity)
   *
   * # Example (JavaScript)
   * ```js
   * sim.spawnCreatures(100); // Spawn 100 creatures
   * ```
   */
  spawnCreatures(count: number): void
  /**
   * Spawn creature at specific position with optional DNA
   *
   * # Arguments
   * * `x` - X coordinate
   * * `y` - Y coordinate
   * * `dna_size_gene` - Optional size gene (0.0-1.0)
   * * `dna_fov_gene` - Optional FOV gene (0.0-1.0)
   *
   * # Errors
   * * Simulation not started
   * * Command queue full
   */
  spawnCreatureAt(x: number, y: number, dnaSizeGene?: number | undefined | null, dnaFovGene?: number | undefined | null): void
  /**
   * Despawn all creatures
   *
   * # Errors
   * * Simulation not started
   * * Command queue full
   */
  killAll(): void
  /**
   * Set simulation pause state
   *
   * # Arguments
   * * `paused` - true to pause, false to resume
   *
   * # Errors
   * * Simulation not started
   * * Command queue full
   */
  setPaused(paused: boolean): void
  /** Get current pause state */
  isPaused(): boolean
  /**
   * Set simulation time scale
   *
   * # Arguments
   * * `scale` - Time multiplier (1.0 = normal, 2.0 = 2x speed, 0.5 = half speed)
   *
   * # Errors
   * * Simulation not started
   * * Command queue full
   */
  setTimeScale(scale: number): void
  /** Get current time scale */
  getTimeScale(): number
  /**
   * Set viewport bounds for culling
   *
   * When enabled, export_positions() only sends creatures within these bounds.
   * The frontend uses ID-based interpolation, so creatures can enter/leave
   * the viewport without causing visual artifacts.
   *
   * # Arguments
   * * `min_x` - Left edge of viewport in world units
   * * `min_y` - Bottom edge of viewport in world units
   * * `max_x` - Right edge of viewport in world units
   * * `max_y` - Top edge of viewport in world units
   * * `margin` - Extra padding around viewport (prevents pop-in at edges)
   *
   * # Errors
   * * Simulation not started
   * * Command queue full
   */
  setViewportBounds(minX: number, minY: number, maxX: number, maxY: number, margin: number): void
  /**
   * Load trial configuration
   *
   * # Arguments
   * * `template` - Trial template name (e.g., "flocking_test")
   * * `randomize_dna` - If true, each creature gets unique random DNA
   * * `dna_size_gene` - Optional size gene (0.0-1.0, used when randomize_dna is false)
   * * `dna_fov_gene` - Optional FOV gene (0.0-1.0, used when randomize_dna is false)
   */
  loadTrial(template: string, randomizeDna: boolean, dnaSizeGene?: number | undefined | null, dnaFovGene?: number | undefined | null): void
  /**
   * Select a creature for perception debug visualization
   *
   * When a creature is selected, the simulation will include detailed
   * perception data (position, range, neighbors) in telemetry updates.
   *
   * # Arguments
   * * `creature_id` - The creature ID to select, or None to clear selection
   *
   * # Example (JavaScript)
   * ```js
   * // Select creature 123 for debug visualization
   * sim.selectCreatureDebug(123);
   *
   * // Clear selection
   * sim.selectCreatureDebug(null);
   * ```
   */
  selectCreatureDebug(creatureId?: number | undefined | null): void
  /**
   * Get full telemetry snapshot (all 45+ metrics)
   *
   * **Performance:** 3-8µs per call (negligible overhead)
   *
   * # Returns
   * JSON string with complete telemetry data:
   * - tick, creatureCount (always included)
   * - systemTimings (always included)
   * - hardwareMetrics (dev-tools only)
   * - parallelizationMetrics (dev-tools only)
   *
   * # Example (JavaScript)
   * ```js
   * const telemetryJson = sim.getTelemetry();
   * const data = JSON.parse(telemetryJson);
   * console.log('Tick:', data.tick);
   * console.log('Creatures:', data.creatureCount);
   * console.log('Movement system:', data.systemTimings.movementUs, 'μs');
   * ```
   */
  getTelemetry(): string
  /**
   * Get current simulation tick
   *
   * # Returns
   * Current tick number (0 if not started or error)
   *
   * # Example (JavaScript)
   * ```js
   * const tick = sim.getTick();
   * console.log('Current tick:', tick);
   * ```
   */
  getTick(): number
  /**
   * Get simulation tick rate (Hz)
   *
   * # Returns
   * Tick rate in Hz (default: 30.0)
   *
   * # Example (JavaScript)
   * ```js
   * const tickRate = sim.getTickRate();
   * console.log('Tick rate:', tickRate, 'Hz');
   * ```
   */
  getTickRate(): number
  /**
   * Get current creature count
   *
   * # Returns
   * Number of living creatures (0 if not started or error)
   *
   * # Example (JavaScript)
   * ```js
   * const count = sim.getCreatureCount();
   * console.log('Creature count:', count);
   * ```
   */
  getCreatureCount(): number
  /**
   * Get the actual number of creatures in the current buffer
   *
   * This returns the exact count of creatures that were exported to the buffer
   * on the last tick. Unlike getCreatureCount() which reads from telemetry
   * (updated every 30 ticks), this is always current.
   *
   * # Returns
   * Number of creatures in buffer (updated every tick)
   *
   * # Example (JavaScript)
   * ```js
   * const bufferCount = sim.getBufferCreatureCount();
   * console.log('Buffer creature count:', bufferCount);
   * ```
   */
  getBufferCreatureCount(): number
  /**
   * Get buffer capacity statistics
   *
   * Returns capacity, used count, and utilization percentage for monitoring
   *
   * # Returns
   * JSON string with buffer stats: { capacity, used, utilizationPct }
   *
   * # Example (JavaScript)
   * ```js
   * const stats = JSON.parse(sim.getBufferStats());
   * console.log(`Buffer: ${stats.used}/${stats.capacity} (${stats.utilizationPct}%)`);
   * ```
   */
  getBufferStats(): string
  /**
   * Stop simulation gracefully (with optional shutdown save)
   *
   * **Note:** Also called automatically when SimulationEngine is dropped
   */
  stop(): void
  /**
   * Shutdown simulation with final save state
   *
   * Sets the running flag to false, which triggers the thread to:
   * 1. Exit the run loop
   * 2. Create a shutdown save (if enabled, lines 293-301)
   * 3. Clean exit
   *
   * Should be called before process exit for proper state preservation.
   */
  shutdown(): void
  /**
   * Get perception debug buffer
   *
   * Returns Float32Array with perception debug data for selected creature.
   * See `ipc/bridge/perception_debug_buffer.rs` for canonical buffer layout.
   */
  getPerceptionDebug(): Float32Array
  /**
   * Fill a JS-owned buffer with perception debug data (zero-allocation)
   *
   * **MEMORY FIX:** JS creates buffer once, Rust fills it every poll.
   * This avoids the per-call Float32Array allocation that V8 doesn't GC properly.
   *
   * # Arguments
   * * `buffer` - JS-owned Float32Array to fill (must be 605+ elements)
   *
   * # Returns
   * true if has_data flag is set (creature selected), false otherwise
   *
   * # Safety
   * Uses as_mut() which is safe because JS polling is single-threaded and
   * we only access the buffer during this synchronous call.
   */
  fillPerceptionDebug(buffer: Float32Array): boolean
  /**
   * Returns the required buffer size for perception debug data.
   * Use this to allocate the correct buffer size in JS.
   */
  getPerceptionDebugBufferSize(): number
}
