# Catatonic Crowd
#
# Purpose: Large population of catatonic crits
# This trial tests huge population size whilst avoiding heavy computation systems

name = "Catatonic Crowd"
description = """
"""

[[spawns]]
type = "grid"
start_x = -30
start_y = -30
spacing = 0.8571
rows = 71
cols = 71
creature_type = "catatonic"